ecrCredsSecret: awsecr-cred

frontend:
  name: frontend

  deployment:
    replicaCount: 1
    image:
      repository: 983988120210.dkr.ecr.eu-north-1.amazonaws.com/frontend-service
      tag: latest
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"

  service:
    type: ClusterIP
    port: 80

  gateway:
    name: main-gateway
    class: nginx
    listeners:
    - name: http
      protocol: HTTP
      port: 80

  httpRoute:
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /

core:
  name: core

  deployment:
    replicaCount: 1
    image:
      repository: 983988120210.dkr.ecr.eu-north-1.amazonaws.com/core-service
      tag: latest
    lifecycle:
      postStart:
        command:
        - python
        - manage.py
        - migrate
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    secretRef: core-secret

  configMap:
    name: core-env
    data:
      DEBUG: "True"
      DB_HOST: "db"
      DB_PORT: "5432"
      ALLOWED_HOSTS: "localhost"
      FRONTEND_SERVICE_URL: "http://example.com"
      EMAIL_SERVICE_URL: "http://example.com"
      MAP_SERVICE_BASE_URL: "http://example.com"
      VOTING_SERVICE_URL: "http://example.com"

  service:
    type: ClusterIP
    port: 8000

  httpRoute:
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /core/api/v1

email:
  name: email

  deployment:
    replicaCount: 1
    image:
      repository: 983988120210.dkr.ecr.eu-north-1.amazonaws.com/email-service
      tag: latest
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"
    secretRef: email-secret

  configMap:
    name: email-env
    data:
      ALLOWED_ROLES: "Gold"
      SMTP_HOST: "mailhog"
      SMTP_PORT: ""
      FROM_EMAIL: ""

  service:
    type: ClusterIP
    port: 8081

  httpRoute:
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /email

map:
  name: map

  deployment:
    replicaCount: 1
    image:
      repository: 983988120210.dkr.ecr.eu-north-1.amazonaws.com/map-service
      tag: latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    secretRef: map-secret

  configMap:
    name: map-env
    data:
      DB_HOST: "db"
      DB_PORT: "5432"
      AWS_REGION: "eu-north-1"

  service:
    type: ClusterIP
    port: 8080

  httpRoute:
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /map/api/artifacts

voting:
  name: voting

  deployment:
    replicaCount: 1
    image:
      repository: 983988120210.dkr.ecr.eu-north-1.amazonaws.com/voting-service
      tag: latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    secretRef: voting-secret

  configMap:
    name: voting-env
    data:
      DB_HOST: "db"
      DB_PORT: "5432"

  service:
    type: ClusterIP
    port: 8085

  httpRoute:
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /voting/api/polls
