frontend:
  name: frontend
  
  deployment:
    replicaCount: 1
    image:
      repository: 983988120210.dkr.ecr.eu-north-1.amazonaws.com/frontend-service
      tag: latest
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"

  service:
    type: ClusterIP
    port: 80

  gateway:
    name: main-gateway
    class: nginx
    listeners:
    - name: http
      protocol: HTTP
      port: 80

  httpRoute:
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
