apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.voting.configMap.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.voting.configMap.name }}
    {{- include "secret-society.labels" . | nindent 4 }}
{{- with .Values.voting.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
