apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
  rules:
    {{- range .Values.httpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
      backendRefs:
      - name: {{ include "frontend.fullname" . }}
        port: {{ .Values.service.port }}
